# Generated by Django 4.2.7 on 2023-11-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_node', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_plante', models.CharField(max_length=30, null=True)),
                ('id_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlante.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='id_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlante.salle'),
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPlante.node')),
            ],
        ),
    ]
