# Generated by Django 4.2.7 on 2023-11-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPlante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='height',
            new_name='light',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='datetime',
        ),
    ]
